server:
  port: 8089
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgress}
    driver-class-name: org.postgresql.Driver
    username: ${DBMS_USERNAME:postgres}
    password: ${DBMS_PASSWORD:123456}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  ai:
    vertex:
      ai:
        gemini:
          project-id: ecommerce-chatbot
          location: us-central1
          api-key: ${GEMINI_API_KEY:AIzaSyDq9DEMNpoqeUeaUsp5KnpQ0clMmeVCheA}
          chat:
            options:
              model: gemini-1.5-flash
              temperature: 0.7
              max-tokens: 2000

api:
  prefix: /api/v1
jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey: syfHZFETm48lXne7m2pPRY7M1XDMK7MTDfO351PbbV0=

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
    com:
      project:
        ecommerce=DEBUG:
vnpay:
  pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "${VNPAY_RETURN_URI:http://localhost:4200/payments/payment-callback}"
  tmn-code: "1AFGVYUH" # Add your TMN code here
  secret-key: "45I9OY4MVOJO00CM9TA4S8X773RAKKXB" # Add your secret key here
  api-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"

# Google Gemini AI Configuration
gemini:
  api:
    key: AIzaSyDq9DEMNpoqeUeaUsp5KnpQ0clMmeVCheA
    url: https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent
    model: gemini-1.5-flash
    max-tokens: 2000
    temperature: 0.7